### ISSUE TITLE
compile this part in qt 5.2, many errors,

### ISSUE THREAD

**Issue by qdsjx1989** [188080501/JQHttpServer#10]
library/JQLibrary/src/JQHttpServer.cpp: In member function ‘bool JQHttpServer::AbstractManage::startServerThread()’:
library/JQLibrary/src/JQHttpServer.cpp:804:7: error: no matching function for call to ‘run(QThreadPool*, JQHttpServer::AbstractManage::startServerThread()::<lambda()>)’
     } );
       ^
In file included from /usr/include/qt5/QtConcurrent/QtConcurrent:14:0,
                 from library/JQLibrary/src/JQHttpServer.cpp:34:
/usr/include/qt5/QtConcurrent/qtconcurrentrun.h:70:12: note: candidate: template<class T> QFuture<T> QtConcurrent::run(T (*)())
 QFuture<T> run(T (*functionPointer)())
            ^~~
/usr/include/qt5/QtConcurrent/qtconcurrentrun.h:70:12: note:   template argument deduction/substitution failed:
library/JQLibrary/src/JQHttpServer.cpp:804:7: note:   mismatched types ‘T()’ and ‘QThreadPool’
     } );
       ^
In file included from /usr/include/qt5/QtConcurrent/QtConcurrent:14:0,
                 from library/JQLibrary/src/JQHttpServer.cpp:34:
/usr/include/qt5/QtConcurrent/qtconcurrentrun.h:75:12: note: candidate: template<class T, class Param1, class Arg1> QFuture<T> QtConcurrent::run(T (*)(Param1), const Arg1&)
 QFuture<T> run(T (*functionPointer)(Param1), const Arg1 &arg1)
            ^~~

**Comment by 188080501** [comment]
感谢反馈，正在修复

**Comment by 188080501** [comment]
推荐 Qt5.7.0 或者更高版本，以及支持 C++11 的编译器（例如VS2013或者更高）
