### ISSUE TITLE
希望能提供下接口说明啊，谢谢！

### ISSUE THREAD

**Issue by waterzch** [188080501/JQHttpServer#11]

**Comment by 188080501** [comment]
目前只有demo
demo内部有简单的说明
https://github.com/188080501/JQHttpServer/tree/master/demos

**Comment by waterzch** [comment]
好的，谢谢！demo看过了，但是比较简单，我的重点是https client。

**Comment by 188080501** [comment]
https client的话，Qt那边直接有提供。
我这里也有简单的封装，你可以参考下

**Comment by waterzch** [comment]
好的，谢谢。再请问，linux不能使用patch吗？为什么啊？

**Comment by 188080501** [comment]
Linux下缺少这个实现，至少我之前用的时候是这样的，不知道Qt新版本里加上了没
