### ISSUE TITLE
为什么linux下不能用patch

### ISSUE THREAD

**Issue by waterzch** [188080501/JQHttpServer#13]
请问为什么linux下将patch函数注释掉了？
如何替代同样功能？

**Comment by 188080501** [comment]
Qt在linux下没提供patch

**Comment by waterzch** [comment]
我看您使用了auto reply = manage_.sendCustomRequest( request, "PATCH", body );来实现patch，加了宏判断，代码log中说编译错误。但是我在ubuntu16.04下qt5.9.1，将宏判断去掉了，可以编译通过。不知道这样是否可以正常工作呢？

**Comment by 188080501** [comment]
编译通过就应该没问题了，可以请求下试试
