### ISSUE TITLE
访问一次会有两次处理

### ISSUE THREAD

**Issue by mostcute** [188080501/JQHttpServer#14]
用浏览器访问一次，服务器显示处理了两次
第一次为正常请求
Body ""
Header QMap(("Accept", "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8")("Accept-Encoding", "gzip, deflate")("Accept-Language", "zh-CN,en-US;q=0.8")("Cache-Control", "max-age=0")("Connection", "keep-alive")("Host", "191.167.2.36:23412")("Upgrade-Insecure-Requests", "1")("User-Agent", "Mozilla/5.0 (Linux; Android 7.1.1; 1801-A01 Build/NMF26X; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/59.0.3071.82 Mobile Safari/537.36")("X-Requested-With", "org.qtproject.example.minibrowser"))
Method "GET"
UrlPath ""
Url "/"
UrlQuery QMap()
UrlPathSplitToList ()
第二次为/favicon 请求打印出来如下
Body ""
Header QMap(("Accept", "image/webp,image/apng,image/*,*/*;q=0.8")("Accept-Encoding", "gzip, deflate")("Accept-Language", "zh-CN,en-US;q=0.8")("Connection", "keep-alive")("Host", "191.167.2.36:23412")("Referer", "http://191.167.2.36:23412/")("User-Agent", "Mozilla/5.0 (Linux; Android 7.1.1; 1801-A01 Build/NMF26X; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/59.0.3071.82 Mobile Safari/537.36")("X-Requested-With", "org.qtproject.example.minibrowser"))
Method "GET"
UrlPath "/favicon.ico"
Url "/favicon.ico"
UrlQuery QMap()
UrlPathSplitToList ("favicon.ico")

不知道为什么会有两次

**Comment by 188080501** [comment]
是浏览器请求小图标用的，如果你只是开发api接口的话，忽略就行
