### ISSUE TITLE
如何加入websocket有思路吗?

### ISSUE THREAD

**Issue by huchangquan** [188080501/JQHttpServer#16]
你好, 我用了它进行服务器开发, 需要加入websocket向客户端广播消息. 有一些思路吗?

**Comment by 188080501** [comment]
请参考QWebSocket和QWebSocketServer，Qt已经提供了现成的接口

**Comment by huchangquan** [comment]
是这样的前端用的js语言中的socket.io, 它有.on和.off功能, 服务器本身TCP监听了端口:7100, 这时网页可以通过url请求到服务端,  不知道如何通过url请求与服务器再绑定一个websocket... 这其中的关系我不是很清楚...
