### ISSUE TITLE
请问中文乱码怎么处理下？

### ISSUE THREAD

**Issue by qhs1573** [188080501/JQHttpServer#17]
我测试过程中发现服务端不能设置编码集，客户端发中文json过去后乱码，请问下有没有解决方法。

**Comment by 188080501** [comment]
请参考replyText接口的实现，返回的内容默认是UTF8编码

**Comment by 188080501** [comment]
另外目前没有提供设置编码的接口，如果需要设置编码需要手动修改源码。
但是从接口实用性上我建议就是使用UTF8编码，不要用其他编码

**Comment by qhs1573** [comment]
> 另外目前没有提供设置编码的接口，如果需要设置编码需要手动修改源码。
> 但是从接口实用性上我建议就是使用UTF8编码，不要用其他编码

感谢 大佬，我发送端本身设置的就是UTF-8不知道为什么服务器端收到后是乱码 但是还是感谢，应该是我这边没处理好，五一放假了好好研究下。
