### ISSUE TITLE
Error SSL while running HttpsServerDemo

### ISSUE THREAD

**Issue by MartinTobing** [188080501/JQHttpServer#18]
When starting the application "HttpsServerDemo", i got this error:
qt.network.ssl: QSslSocket: cannot resolve TLSv1_1_client_method
qt.network.ssl: QSslSocket: cannot resolve TLSv1_2_client_method
qt.network.ssl: QSslSocket: cannot resolve TLSv1_1_server_method
qt.network.ssl: QSslSocket: cannot resolve TLSv1_2_server_method
qt.network.ssl: QSslSocket: cannot resolve SSL_select_next_proto
qt.network.ssl: QSslSocket: cannot resolve SSL_CTX_set_next_proto_select_cb
qt.network.ssl: QSslSocket: cannot resolve SSL_get0_next_proto_negotiated
qt.network.ssl: QSslSocket: cannot resolve SSL_set_alpn_protos
qt.network.ssl: QSslSocket: cannot resolve SSL_CTX_set_alpn_select_cb
qt.network.ssl: QSslSocket: cannot resolve SSL_get0_alpn_selected
sslCertificate: QSslCertificate("1", "ae:01:71:c8:21:fc:00:c2", "eKXBjkCzjZbWnEvw5NXsWw==", ("Internet Widgits Pty Ltd"), ("Internet Widgits Pty Ltd"), QMap(), QDateTime(2017-04-09 07:07:27.000 UTC Qt::TimeSpec(UTC)), QDateTime(2027-04-07 07:07:27.000 UTC Qt::TimeSpec(UTC)))
sslKey: QSslKey(PrivateKey, RSA, 2048)
caCertificates: ()
listen: true

And when i send packet data to the server, the server got error like this:
qt.network.ssl: QSslSocket: cannot call unresolved function TLSv1_2_server_method
qt.network.ssl: QSslSocket: cannot call unresolved function TLSv1_2_server_method

could you help me, why this happens ?

**Comment by 188080501** [comment]
这类错误多半是因为你的缺少ssl的环境，比如说在windows下你可能需要在exe同目录下有这些dll
libssl-1_1-x64.dll
libcrypto-1_1-x64.dll

你可以在
https://slproweb.com/products/Win32OpenSSL.html
下载你缺少的库

**Comment by zincent** [comment]
大佬我编译不过，找不到qApp  这个东西，请问市是什么原因

**Comment by zincent** [comment]
没问题了，我加了个QCoreApplication头文件就好了，我一直以为qApp是您定义的变量
