### ISSUE TITLE
my server can`t run

### ISSUE THREAD

**Issue by chyxddhao** [188080501/JQHttpServer#19]

**Comment by 188080501** [comment]
什么报错？

**Comment by chyxddhao** [comment]
比如httpserverDemo ,我直接运行的时候会提示listen:false进去看了一下代码，最后一层的的tcpserver_.inNUll返回空，小白准备用Qt做一个http服务器~参考了大佬的代码，但是不知道如何更改




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Jason"<notifications@github.com&gt;; 
发送时间: 2020年6月26日(星期五) 中午11:45
收件人: "188080501/JQHttpServer"<JQHttpServer@noreply.github.com&gt;; 
抄送: "."<443112568@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [188080501/JQHttpServer] my server can`t run (#19)





 
什么报错？

**Comment by 188080501** [comment]
尝试修改下监听的端口，看看监听是否能成功

**Comment by chyxddhao** [comment]
好的谢谢博主 已解决 会跟着代码学习一下，虽然感觉还是有点难了~




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Jason"<notifications@github.com&gt;; 
发送时间: 2020年6月26日(星期五) 中午12:02
收件人: "188080501/JQHttpServer"<JQHttpServer@noreply.github.com&gt;; 
抄送: "."<443112568@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [188080501/JQHttpServer] my server can`t run (#19)





 
尝试修改下监听的端口，看看监听是否能成功
