### ISSUE TITLE
探讨是否可以有 QML 接口

### ISSUE THREAD

**Issue by qyvlik** [188080501/JQHttpServer#2]
在 readme 中提及了并发数的问题。

> 推荐使用Linux系统或者Unix系统，因为在5.7后，Qt更换了Unix相关系统的底层模型，从select更换为了poll，这样子网络库的并发就脱离了1024个的限制。

看起来应该可以应用方向是小型，实用上。

这里我想探讨一下是否可以有 QML 的接口。或者说 QML 的接口该如何设计呢？

**Comment by 188080501** [comment]
直接弄成回调性质，数据全部用JSON
我以前在另外一个基于Qt的网络框架里弄过，后来觉得局限性很大，还是回到C++弄了
