### ISSUE TITLE
SSL Error

### ISSUE THREAD

**Issue by MartinTobing** [188080501/JQHttpServer#20]
When i run this JQHttpServer using my valid ssl certification with digicert cert, Got error from third party enggine : "SSL routines:tls_process_server_certificate:certificate verify failed". And also got error message from the application : "JQHttpServer::Session::inspectionBuffer: error3: HEAD". Could you help me to solve this problem?

Thank you.

**Comment by 188080501** [comment]
1. 请用POSTMAN测试HTTP接口调用，若还发生错误请将完整的URL、参数、报错内容截图
2. 服务端是否使用的是HttpsServerDemo?

**Comment by MartinTobing** [comment]
Yes, i'm using HttpsServerDemo. Actually i tried to set webhook from telegram api to your HttpsServerDemo. I added a domain name and point to HttpsServerDemo. Nothing happened. When i check from https://api.telegram.org/bot[myToken]/getWebHookInfo , it said:
{"ok":true,"result":{"url":"https://api.myapp.com","has_custom_certificate":false,"pending_update_count":0,"last_error_date":1593487302,"last_error_message":"SSL error {error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed}","max_connections":40}}

Do you have any solution about it? And i have one more question, how can i add the "SSLCertificateChainFile" to your HttpsServerDemo ?

Thank you for your concern.

**Comment by 188080501** [comment]
1. 请使用POSTMAN测试接口
2. 如果无法使用POSTMAN，请在ssl检测网站中测试你的接口，比如说：https://myssl.com/ssl.html 它会告诉你HTTPS接口准确的状态，例如CA证书链是否完整，证书是否有效等

另外如果你没有添加CA证书，那么很可能会出现问题，添加证书的代码如下。注意区分Pem和Der格式

```
 qDebug() << "listen:" << sslServerManage.listen(
                    QHostAddress::Any,
                    24684,
                    "xxx/__xxx_com.crt",
                    "xxx/__xxx_com.key",
                    {
                        { "xxx/__xxx_com.ca-bundle", QSsl::Pem }, // Add your CA here
                        { "xxx/__xxx_com.ca-bundle", QSsl::Pem }, // Add your CA here
                    }
                );
```

**Comment by MartinTobing** [comment]
Thank you. Solved by adding the script you mentioned above.
