### ISSUE TITLE
Add Custom Header in HttpsClientDemo

### ISSUE THREAD

**Issue by MartinTobing** [188080501/JQHttpServer#21]
Could you help me, how to add custom header when running this POST script :
JQNet::HTTP::post( "https://127.0.0.1:24684/TestUrl", "AppendData" );

Thank you for your concern.

**Comment by 188080501** [comment]
QNetworkRequest request( QUrl( "https://xxx.xxx.xxx" ) );
request..setRawHeader( "Content-Type", "application/x-www-form-urlencoded" );
JQNet::HTTP::post( request, "AppendData" );
