### ISSUE TITLE
关于遇到超时的问题

### ISSUE THREAD

**Issue by moruoxian** [188080501/JQHttpServer#23]
你好我使用 您的库 请求 http  有时会发现 就算外网 不可请求到 也是一直阻塞直到超时 才返回 是否可以 立即返回

**Comment by 188080501** [comment]
关于JQNet的HTTP模块，设计本意只是一个简单的封装，放入这里也是为了配合测试所用。模块里面没有判断底层网络情况，只依赖Qt那边的error，所以如果Qt没有error信号就不会返回

**Comment by 188080501** [comment]
你这边遇到的是什么情况？我这里看看如何复现

**Comment by moruoxian** [comment]
> 你这边遇到的是什么情况？我这里看看如何复现



> 关于JQNet的HTTP模块，设计本意只是一个简单的封装，放入这里也是为了配合测试所用。模块里面没有判断底层网络情况，只依赖Qt那边的error，所以如果Qt没有error信号就不会返回

好吧 谢谢 这个库在网络可达的情况下确实很好用 就是有时候纯内网环境情况下 请求外网restful一直阻塞感觉挺别扭的。。

**Comment by moruoxian** [comment]
> > 你这边遇到的是什么情况？我这里看看如何复现
> 
> > 关于JQNet的HTTP模块，设计本意只是一个简单的封装，放入这里也是为了配合测试所用。模块里面没有判断底层网络情况，只依赖Qt那边的error，所以如果Qt没有error信号就不会返回
> 
> 好吧 谢谢 这个库在网络可达的情况下确实很好用 就是有时候纯内网环境情况下 请求外网restful一直阻塞感觉挺别扭的。。

我们采用了这种方法. 在调用http请求之前先通过tcp 判断一下端口是否通 然后再请求。
QTcpSocket *s = new QTcpSocket();
QObject::connect(s, &QTcpSocket::connected, [=]() {
	emit netOk();
}
s->deleteLater();
		});
s->connectToHost(url.host(), url.port());
成功解决超时问题。

**Comment by 188080501** [comment]
之前貌似忘记说了，在JQNet里面有tcpReachable和pingReachable可以用来判断网络可达性

**Comment by 188080501** [comment]
如果问题解决了，那我先关闭这个issue了
