### ISSUE TITLE
关于服务端主动下发的问题

### ISSUE THREAD

**Issue by zlozl233** [188080501/JQHttpServer#27]
您好，我想请问一下，我要实现服务端能主动下发，也就是长连接，我测试每次请求都会有新的连接过来，这时候我保留套接字，然后重新new一个session 来应答，这样是否可行？

**Comment by 188080501** [comment]
你说的需求，就是从S端主动下发数据到C端，这个模式HTTP1.1很难实现（HTTP2可以），JQHttpServer设计时也没考虑这个需求，故也无法实现
如果你要做，建议使用WebSocket，Qt都有提供现成的接口
