### ISSUE TITLE
replyXXX后，怎样才能不关闭连接？

### ISSUE THREAD

**Issue by kevinhwu** [188080501/JQHttpServer#29]
在使用EventSouce时，希望能不关闭连接，但调用replyXXX函数后，总是会关闭连接。需要怎样修改呢？

**Comment by 188080501** [comment]
目前设计里reply后session就不建议再使用
当然理论上session会等待http回复结束再销毁，存在时间差。所以reply后一定时间内还可以继续访问session

**Comment by 188080501** [comment]
为什么不建议使用是因为整个库开发基于http1.1非长连接模式，理论上回复后也不需要再关注session情况，除非是进度监控这些，你有这样需求不

**Comment by kevinhwu** [comment]
感谢回复！我的项目里有服务端推送事件通知的场景，使用了EventSource机制，看来只能换成qhttp了。
