### ISSUE TITLE
用poset man进行post，连续post 3次左右，post man提示 Error: socket hang up 了，前两次post均有返回成功，请问应该怎么解决？

### ISSUE THREAD

**Issue by Theremoons** [188080501/JQHttpServer#30]

**Comment by 188080501** [comment]
这个是postman这边的问题，上一次http连接没彻底断开就直接发起下一次http请求就报错

**Comment by 188080501** [comment]
如果你想缓解这个问题，可以修改
```
void JQHttpServer::Session::onBytesWritten(const qint64 &written)
```

里面的
```
QTimer::singleShot( 1000, this, &QObject::deleteLater );
```

把1000设置到更小的值，这样可以加速session销毁速度

**Comment by 188080501** [comment]
为什么设置1000ms是因为某些环境下如果写入完成就直接断开连接，会导致client这边不能正常接收完数据就断开，因此留了1000ms的余量

**Comment by 188080501** [comment]
此问题已解决
https://github.com/188080501/JQHttpServer/commit/801f463330b1c7941f8ad100da882c2870a4e3eb
