### ISSUE TITLE
Qt新手提问，关于主动关闭https服务

### ISSUE THREAD

**Issue by zw8622402** [188080501/JQHttpServer#31]
https服务在sslServerManage->listen启动成功后如何可以关闭服务？看Demo中好像只有启动没有关闭的代码，请赐教谢谢

**Comment by 188080501** [comment]
直接把Manage释放掉就行

**Comment by zw8622402** [comment]
好的，谢谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "188080501/JQHttpServer"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年10月28日(星期三) 上午8:23
收件人:&nbsp;"188080501/JQHttpServer"<JQHttpServer@noreply.github.com&gt;;
抄送:&nbsp;"张伟"<416729385@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [188080501/JQHttpServer] Qt新手提问，关于主动关闭https服务 (#31)





 
直接把Manage释放掉就行
