### ISSUE TITLE
在IE8，IE9下用XDomainRequest进行请求https

### ISSUE THREAD

**Issue by zhnaglala** [188080501/JQHttpServer#32]
是不是不支持?没法请求成功. 能支持下吗

**Comment by moruoxian** [comment]
> 是不是不支持?没法请求成功. 能支持下吗

实在不行只能自己用原生的qt写了 我试过普通chrom浏览器请求https 是可以的

**Comment by 188080501** [comment]
这个问题已经单独加好友讨论过，同步下结论
初步推测是ssl兼容问题，http版本使用正常。
尝试更换ssl版本也未解决，暂时未找到解决方法

**Comment by 188080501** [comment]
若还有类似问题，请再开issue，此问题关闭
