### ISSUE TITLE
JQHttpServer浏览器请求的时候如何返回一个本地的html页面

### ISSUE THREAD

**Issue by qhs1573** [188080501/JQHttpServer#33]
比如浏览器访问：http://localhost:23412/index

服务器收到index后我想返回一个本地已经写好的html页面，以下是demo中的例子：
session->replyText( QString( "url:%1\nbody:%2" ).arg( session->requestUrl(), QString( session->requestBody() ) ) );
session->replyRedirects( QUrl( "http://www.baidu.com" ) );
session->replyJsonObject( { { { "message", "ok测试部" } } } );
session->replyJsonArray( { "a", "b", "c" } );
session->replyFile( "/Users/jason/Desktop/Test1.Test2" );
session->replyImage( QImage( "/Users/jason/Desktop/Test.png" ) );
session->replyBytes(QByteArray(4,'\x24'));

看到请解释下，非常感谢

**Comment by 188080501** [comment]
简单的说你要允许返回html文件资源
通过replyFile接口
但是自己实现HTML服务器简单的话可以，复杂的话建议还是直接用nginx这些

**Comment by qhs1573** [comment]
这样的问题对你们大神来说很简单 但是对我这个测试的来说有点难耽误你们时间了，感谢 你的回答，我最后把网页用文件流读出来传到replyText里用的，发现还可以用。
