### ISSUE TITLE
关于HttpServerCallback函数中耗时较长的异常问题

### ISSUE THREAD

**Issue by zw8622402** [188080501/JQHttpServer#35]
经测试HttpServerCallback中超过30秒左右没返回，调用方就提示Connection Closed Gracefully.
然后Qt这边就提示JQHttpServer::Session::replyText: current session this is null

**Comment by 188080501** [comment]
因为超时了，所以session被关闭了
如果觉得30秒太短，可以修改下源码内timer的时间长短

**Comment by 188080501** [comment]
https://github.com/188080501/JQHttpServer/blob/6d506ba60fe73817622a1fb915824d75129a44fd/library/JQLibrary/src/jqhttpserver.cpp#L167

**Comment by zw8622402** [comment]
好的，看到了，谢谢
