### ISSUE TITLE
要怎么实现get body部分

### ISSUE THREAD

**Issue by liaohanghua** [188080501/JQHttpServer#37]
put post都可以“const QByteArray &body”，但是get不行，请教大神帮忙解答下。要怎么实现body

**Comment by 188080501** [comment]
一般来说，GET不能带有body，而PUT和POST可以带有body关于method分类可以参考
https://tools.ietf.org/html/rfc2616#page-53

**Comment by liaohanghua** [comment]
先谢谢大神，顺便我发现可以用patch的方式去发送 get body 
我增加了个接口：
//    auto reply = manage_.sendCustomRequest( request, "PATCH", body );
    auto reply = manage_.sendCustomRequest( request, "GET", body );
我改成GET 之后  实现了我想要的功能定制，我们是需要get里面带有body,也感谢作者源码支持。
