### ISSUE TITLE
https 客户端是怎么支持的呢  下载openssl怎么用

### ISSUE THREAD

**Issue by qq88797833** [188080501/JQHttpServer#39]

**Comment by 188080501** [comment]
https支持Qt已经做了，直接用就行

**Comment by qq88797833** [comment]
需要配置环境变量吗&nbsp; 我http可以用 https 不能用啊



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Jason"<notifications@github.com&gt;; 
发送时间: 2020年12月28日(星期一) 下午5:27
收件人: "188080501/JQHttpServer"<JQHttpServer@noreply.github.com&gt;; 
抄送: "丶"<506916737@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [188080501/JQHttpServer] https 客户端是怎么支持的呢  下载openssl怎么用 (#39)





 
https支持Qt已经做了，直接用就行

**Comment by 188080501** [comment]
不需要配置环境变量，但是在windows系统下可能需要配置ssl相关的dll
具体请使用搜索引擎，本github仓库只讨论server相关问题
