### ISSUE TITLE
别的网站SSL证书检测显示缺少中间证书

### ISSUE THREAD

**Issue by d7185540** [188080501/JQHttpServer#4]
请问一下这个是设置问题么？

**Comment by 188080501** [comment]
代码兼容问题，之前QQ聊过，这里再备注一下
因为最初开发的时候我都是自签名的证书，报警告我都没注意
找个时间我去申请个证书，再仔细测试下

**Comment by 188080501** [comment]
已经增加了CA证书的导入接口
