### ISSUE TITLE
长时间多次post请求会出现内存泄露？

### ISSUE THREAD

**Issue by autumoon** [188080501/JQHttpServer#40]
包含头文件，然后客户端使用示例代码：
const auto &&reply = JQNet::HTTP::post( "http://127.0.0.1:23412/TestUrl", "AppendData" );
进行120ms/次请求，则出现内存不断增长的问题，请问这个问题有什么好的解决方案吗？
服务端正常，客户端出现内存泄露？期待你的交流，我的QQ4589968

**Comment by 188080501** [comment]
https://github.com/188080501/JQHttpServer/commit/38d6cdc101fe7cbf1a85db3bee2435ec92b04ca0
尝试修复内存泄漏问题

**Comment by zhao1989beilong** [comment]
还是有内存泄露的情况。楼主

**Comment by autumoon** [comment]
> 
> 
> 还是有内存泄露的情况。楼主

请求部分可以自己写 这部分内存泄露确实还没有被完全修复

**Comment by zhao1989beilong** [comment]
> > 还是有内存泄露的情况。楼主
> 
> 请求部分可以自己写 这部分内存泄露确实还没有被完全修复

你好，这边有没有用数据库啊，qt5.12后跨线程调取数据库有问题，但是不在回调里面调取数据库的话没有头绪。。

**Comment by 188080501** [comment]
https://github.com/188080501/JQHttpServer/pull/55
貌似是这个问题相关？已经复用了manage，问题暂时关闭，如果还有请反馈

**Comment by zhao1989beilong** [comment]
你的邮件我已经收到
