### ISSUE TITLE
用于地图瓦片数据的发布中的优化建议（tms）

### ISSUE THREAD

**Issue by joe-ieta** [188080501/JQHttpServer#43]
Hi 188080501 
我用JQHttp 发布地图瓦片数据，使用稳定。希望增加一个针对地图数据特点的 replyTmsImage，对地图数据进行预读与缓存，提高地图数据的相应速度。TMS格式的地图瓦片数据访问有一定的规律，简单说就是将当前访问的图片文件的前后图片预读，或者使用进行缓存，缓存数量可以通过参数设定。谢谢！

**Comment by 188080501** [comment]
Hi，感谢建议
但是我没用使用过TMS，不了解其原理，因此暂时无法对此数据结果做专门优化。
你可以参考下replyBytes接口，自己开发一个特化版本的replyTmsImage

另外一般来说，操作系统都会自己做文件缓存，假设你收到的是请求5号数据，可以在外部用QFile直接去读取前后数据，例如4和6，这样子下一次真的请求4或者6号数据的时候速度就会非常快。

**Comment by joe-ieta** [comment]
感谢回复！

**Comment by 188080501** [comment]
若还有类似问题，请再开issue，此问题关闭
