### ISSUE TITLE
如何在session中返回一个自定义的错误？

### ISSUE THREAD

**Issue by joe-ieta** [188080501/JQHttpServer#48]
你好，感谢上一次的回复建议。
这里请教一个问题：就是如何在session中返回一个自定义错误？
代码：

    static JQHttpServer::TcpServerManage httpServer( maxThreads ); // 设置最大处理线程数，默认2个
    httpServer.setHttpAcceptedCallback( std::bind(onHttpAccepted, std::placeholders::_1 ) );

设置了onHttpAccepted 回调函数，同时在Session 中增加了一个自定义错误代码 internalErrorCode_, 
通过如下代码暴露出来：
int JQHttpServer::Session::internalErrorCode() const
{
   // JQHTTPSERVER_SESSION_PROTECTION( "internalErrorCode", 0 )

    return internalErrorCode_;
}

在session的 replyImage中修改internalErrorCode_，该值在回调函数中不能获得（修改没起作用），是不是哪里有问题 ？
尝试修改：
int JQHttpServer::Session::replyHttpCode() const
中的 replyHttpCode返回，也没有效果，不知是哪里问题？请教！

在次感谢！

**Comment by 188080501** [comment]
你要返回自定义的HTTP错误码吗？

**Comment by 188080501** [comment]
http这边着几个方式来返回你的错误
通过http错误码
返回的header
返回的body

一般来说不会用header来包含错误信息，都是用http错误码配合body的内容（例如json）

**Comment by joe-ieta** [comment]
谢谢！
另外再请教一个问题，就是在setHttpAcceptedCallback( std::bind(onHttpAccepted, std::placeholders::_1 ) ) 中，onHttpAccepted函数是一个全局静态函数，大量的并发访问时，该函数时运行在各个SESSION的线程中的吗？在该函数这里有没有性能或并发问题？
谢谢！

**Comment by 188080501** [comment]
这里传进去的是一个回调，写lambda也可以，不一定是全局的
处理回调有专用的线程，不是socket的生存线程，具体开几个线程是可以设置的
性能问题的话，只能说够用，要做上万QPS会有压力，10万以上受限于Qt这里做不到

**Comment by joe-ieta** [comment]
感谢！通过增加一个回调函数等方法，处理了地图数据tms的高效率访问以及错误处理，用于GIS数据发布成WTMS协议，在工程环境中已经够用了。再次感谢！
