### ISSUE TITLE
静态路由使用不便

### ISSUE THREAD

**Issue by zhangzy7** [188080501/JQHttpServer#50]
现在使用静态路由要自行实现 sessionAccepted 函数，颇为不便，建议增加专用的静态路由功能

**Comment by 188080501** [comment]
目前可以根据moc系统，自动映射到槽函数，具体请看
https://github.com/188080501/JQHttpServer/issues/36

**Comment by zhangzy7** [comment]
抱歉，是我指代不明，其实我想说的是静态文件路由。
目前我是实现 sessionAccepted 函数，通过后缀正则匹配过滤请求，最后 replyFile 。如果这块也可以通过 moc 自动绑定就好了。
