### ISSUE TITLE
Qt6支持

### ISSUE THREAD

**Issue by ALittleDruid** [188080501/JQHttpServer#52]
使用Qt6.3.0编译失败

JQHttpServer\library\JQLibrary\src\jqhttpserver.cpp(1633): error C2039: "midRef": 不是 "QString" 的成员

可以用mid方法或者QstringView.mid方法代替

**Comment by daabtech** [comment]
您好，您的邮件我已经收到，我将在最短的时间内作出回复，谢谢，祝  万事如意！

**Comment by 188080501** [comment]
针对大于5.10的版本，已经修改为QStringView
https://github.com/188080501/JQHttpServer/commit/9e6cc4205507befddedde64bf85beed88f357f0f

**Comment by 188080501** [comment]
感谢反馈
