### ISSUE TITLE
win10和ubuntu 16.04下性能测试问题，每个请求20ms

### ISSUE THREAD

**Issue by mileden** [188080501/JQHttpServer#8]
你好，我在win10和ubuntu 16.04下进行性能测试（Qt5.7），发现单次请求、响应时间延迟非常大，每个请求20ms左右。

测试方法为：在同一台电脑上先启动HttpServerDemo，然后运行HttpClientDemo，在client端发起5000次请求（单线程，即在main线程内），方法同benchMarkFor5000，并计算时间。测试过程中，两个进程的cpu利用率以及系统cpu利用率都很低。

折算下来，空跑QPS才50，请问这可能是什么原因导致性能上不去？

**Comment by 188080501** [comment]
因为是同步阻塞的HTTP请求，所以速度特别慢，也无法发挥出系统的性能。如果要测试QPS，你可以看下专业的测试工具。

**Comment by flydvip** [comment]
你好，我在WIN１０＋QT5.9.7+VS2015 64bit环境下，编译没有错误，但是打开DEMO都没有反应，请问如何进行测试？？

**Comment by 188080501** [comment]
打开的是哪个Demo？ 另外于本Issues无关的问题请新开Issuse
