### ISSUE TITLE
server端程序运行崩溃

### ISSUE THREAD

**Issue by mileden** [188080501/JQHttpServer#9]
在CPU负载较高，或回调执行时间较长下，程序可能崩溃。
看了下代码，回调是在另一个线程下运行，当调用session->reply时，session，iodeviece_都有可能**随时**被删除（如超时）；
另外，如果客户端提前超时，关闭连接，那么服务端对accept的TcpSocket未做处理，这种场景下程序运行行为如何，是否导致ioDevice_指向已销毁的socket资源。

**Comment by 188080501** [comment]
有可能发生这样的事情，所以reply里面增加了对this的空指针判断
但是目前的解决方案不是100%好用，也存在意外的情况

**Comment by liulin188** [comment]
为什么要做超时销毁呢，不设置超时可否？

**Comment by 188080501** [comment]
socket必须做超时销毁，比如说30秒自动关闭。如果有需要可以自己调整下超时时间

**Comment by 188080501** [comment]
另外关于null的this，在这个库开发好到现在已经加了很多道判断，现在基本能保证跨线程时正常工作
另外socket提前关闭，且不发送任何数据时timer会存在不启动，进而导致session未销毁的情况，也已修复，那么此issues就先关闭了，如果有新情况请反馈，谢谢
